
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'programleftPLUSleftDIVASSIGNOP BEGIN DATATYPE DIV END GT ID LPAR MAIN NUMBER PLUS RETURN RPAR SEMI WHILEprogram : DATATYPE MAIN LPAR RPAR BEGIN stmtblock ENDstmtblock : stmt stmtblockstmtblock : stmt : declstmt : assignstmt : whilestmtstmt : returnstmtdecl : DATATYPE ID ASSIGNOP NUMBER SEMIassign : ID ASSIGNOP expr SEMIexpr : ID PLUS NUMBERexpr : ID DIV NUMBERexpr : NUMBERexpr : IDwhilestmt : WHILE LPAR cond RPAR stmtblock END WHILEcond : ID GT NUMBERreturnstmt : RETURN ID SEMI'
    
_lr_action_items = {'DATATYPE':([0,6,9,10,11,12,13,29,33,34,36,42,],[2,7,7,-4,-5,-6,-7,-16,-9,7,-8,-14,]),'$end':([1,18,],[0,-1,]),'MAIN':([2,],[3,]),'LPAR':([3,15,],[4,21,]),'RPAR':([4,27,40,],[5,34,-15,]),'BEGIN':([5,],[6,]),'END':([6,8,9,10,11,12,13,19,29,33,34,36,39,42,],[-3,18,-3,-4,-5,-6,-7,-2,-16,-9,-3,-8,41,-14,]),'ID':([6,7,9,10,11,12,13,16,20,21,29,33,34,36,42,],[14,17,14,-4,-5,-6,-7,22,24,28,-16,-9,14,-8,-14,]),'WHILE':([6,9,10,11,12,13,29,33,34,36,41,42,],[15,15,-4,-5,-6,-7,-16,-9,15,-8,42,-14,]),'RETURN':([6,9,10,11,12,13,29,33,34,36,42,],[16,16,-4,-5,-6,-7,-16,-9,16,-8,-14,]),'ASSIGNOP':([14,17,],[20,23,]),'NUMBER':([20,23,31,32,35,],[26,30,37,38,40,]),'SEMI':([22,24,25,26,30,37,38,],[29,-13,33,-12,36,-10,-11,]),'PLUS':([24,],[31,]),'DIV':([24,],[32,]),'GT':([28,],[35,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'stmtblock':([6,9,34,],[8,19,39,]),'stmt':([6,9,34,],[9,9,9,]),'decl':([6,9,34,],[10,10,10,]),'assign':([6,9,34,],[11,11,11,]),'whilestmt':([6,9,34,],[12,12,12,]),'returnstmt':([6,9,34,],[13,13,13,]),'expr':([20,],[25,]),'cond':([21,],[27,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> DATATYPE MAIN LPAR RPAR BEGIN stmtblock END','program',7,'p_program','lalr_parser.py',63),
  ('stmtblock -> stmt stmtblock','stmtblock',2,'p_stmtblock_multi','lalr_parser.py',68),
  ('stmtblock -> <empty>','stmtblock',0,'p_stmtblock_empty','lalr_parser.py',72),
  ('stmt -> decl','stmt',1,'p_stmt_decl','lalr_parser.py',76),
  ('stmt -> assign','stmt',1,'p_stmt_assign','lalr_parser.py',80),
  ('stmt -> whilestmt','stmt',1,'p_stmt_while','lalr_parser.py',84),
  ('stmt -> returnstmt','stmt',1,'p_stmt_return','lalr_parser.py',88),
  ('decl -> DATATYPE ID ASSIGNOP NUMBER SEMI','decl',5,'p_decl','lalr_parser.py',92),
  ('assign -> ID ASSIGNOP expr SEMI','assign',4,'p_assign','lalr_parser.py',96),
  ('expr -> ID PLUS NUMBER','expr',3,'p_expr_plus','lalr_parser.py',100),
  ('expr -> ID DIV NUMBER','expr',3,'p_expr_div','lalr_parser.py',104),
  ('expr -> NUMBER','expr',1,'p_expr_num','lalr_parser.py',108),
  ('expr -> ID','expr',1,'p_expr_id','lalr_parser.py',112),
  ('whilestmt -> WHILE LPAR cond RPAR stmtblock END WHILE','whilestmt',7,'p_whilestmt','lalr_parser.py',116),
  ('cond -> ID GT NUMBER','cond',3,'p_cond','lalr_parser.py',120),
  ('returnstmt -> RETURN ID SEMI','returnstmt',3,'p_returnstmt','lalr_parser.py',124),
]
